### ISSUE TITLE
Error executing instructions for: Set up Angular app - I also tried with sudo.

### ISSUE THREAD

**Issue by superrandres** [pselle/django-rest-angular2-example#4]
Thanks for the help.

npm WARN package.json angular2-djangocon-2016@1.0.0 No description
npm WARN package.json angular2-djangocon-2016@1.0.0 No repository field.
npm WARN package.json angular2-djangocon-2016@1.0.0 No README data
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'angular/platform-browser-dynamic' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'angular2-djangocon-2016'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/ronald/PycharmProjects/xample/angular2
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code E404
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ronald/PycharmProjects/xample/angular2/npm-debug.log
npm ERR! not ok code 0

**Comment by djangorobert** [comment]
how do you use this when launching it with a real website im using pythonanywhere.com ? 
any suggestions the api is working but the angular index im not seeing would i need to make a view for the index page ? thanks

**Comment by pselle** [comment]
Thanks for the report, but I was unable to replicate :/ It looks like the package is there when I tried.
