### ISSUE TITLE
Production

### ISSUE THREAD

**Issue by djangorobert** [pselle/django-rest-angular2-example#5]
Not seeing any explaination on how to do this project with Production of course with developement no problem but as for production not seeing any solution i currently am trying to get this to work with Production but have run into a problem with getting it to work . 

Wanted to see if anyone else has had the same issue I am using pythonanywhere.com and seems to work with the api but when i am trying to use the Angular side not geting anything to show. 

Could you please update it to work with the production side. thanks

**Comment by pselle** [comment]
@djangorobert This is an example app (not meant for production), but if you want to compile for production purposes, I would suggest using webpack to build the angular2 app, and hosting that on a static instance (such as S3), or by uploading the static files to your webserver. I made an issue to update the repo for webpack (#7) but that's my recommendation.

**Comment by djangorobert** [comment]
Thanks Pam 😃
